### ISSUE TITLE
On Writing Alfred Workflows in Python

### ISSUE THREAD

**Issue by zmoog** [zmoog/zmoog.github.io#5]
## Tasks

- [x] Add an `arduino-cli` for Alfred example
- [x] Notarize `arduino-cli` binary using my identity
- [x] add a link to https://github.com/umbynos/arduino_cli
- [x] Add a Classeviva example
- [x] publish the Alfred Arduino CLI project.
- [ ] Complete draft iterations
- [x] Review images a replace the bad ones (i.e. on-screen typing is not required on GIFs)

### Discarded

- [ ] ~Password generator~
- [ ] ~WTF is my IP?~

## Abstract

[Alfred](https://www.alfredapp.com) is a popular [desktop application luncher](https://en.wikipedia.org/wiki/Comparison_of_desktop_application_launchers) for macOS. Alongside builtin actions, it adds a powerful extension mechanism called Alfred Workflows, that allows developers to write custom workflows and use community ones. 

In this post I will describe how to use Alfred Workflow and the [Alfred-Workflow](https://www.deanishe.net/alfred-workflow/index.html) Python framework to automate common tasks in macOS and use integrare 3rd party services.

### 1. What Am I Really Trying To Say

Alfred is a useful on its own, but the customisable workflows make it powerful empowering user to built on top of Alfred with any language available on macOS.

### 2. Why Should People Care 

Developer can leverage Workflows to build useful UI tools quickly.

### 3. What Is The Most Important Point

Alfred-Workflows offers a rich framework to build Python based tools you can trigger almost instantly with a few key strokes.

### 4. What Is The Easiest Way To Understand The Most Important Point

Show an example.

### 5. How Do I Want The Reader To Feel

Excited about the opportunity and eager to try their own example (download a sample?)

### 6. What Should The Reader Do Next

Download the example and run it!

## Outline

- Automate all the things (reducing friction)
- What is Alfred? (alfred alternatives on other platforms?)
- Workflows
- Introducing Alfred-Workflows
- Example: pwgen, classeviva
- Example: Arduino CLI
- Conclusion
